- basename_vm: racnode-dc1-
  num_vm: 2
  hostgroup: vbox-rac-dc1
  domain: internal.lab
  box: oravirt/ol73
  vagrant_user: vagrant
  vagrant_pass: vagrant
  #vagrant_private_key: /vagrant/base-provision/insecure_private_key
  ram: 6196
  cpu: 1
  base_pub_ip: 192.168.7.10
  base_pub_ip_vip: 192.168.7.110
  scan_addresses: 192.168.7.210,192.168.7.211
  base_priv_ip: 172.16.7.10
  synced_folders:
     - {src: swrepo, dest: /media/swrepo}
     #- {src: /Users/miksan/Downloads/oracle, dest: /media/swrepo}
  create_local_disk: true
  local_disks:
     - {name: u01, size: 75, count: 1}
  create_shared_disk: true
  shared_disks:
     - {name: crs, size: 40, count: 1}
     - {name: data, size: 8, count: 1}
     - {name: fra, size: 15, count: 1}
  provisioning: extra-provision/ansible-oracle/vbox-rac-dc1.yml
  provisioning_env_override: false

# - basename_vm: racnode-dc2-
#   num_vm: 2
#   hostgroup: vbox-rac-dc2
#   domain: internal.lab
#   box: oravirt/ol73
#   vagrant_user: vagrant
#   vagrant_pass: vagrant
#   vagrant_private_key:
#   ram: 6196
#   cpu: 1
#   base_pub_ip: 192.168.8.10
#   base_pub_ip_vip: 192.168.8.110
#   scan_addresses: 192.168.8.210,192.168.8.211
#   base_priv_ip: 172.16.8.10
#   synced_folders:
#      - {src: swrepo, dest: /media/swrepo}
#      #- {src: /Users/miksan/Downloads/oracle, dest: /media/swrepo}
#   create_local_disk: true
#   local_disks:
#     - {name: u01, size: 75, count: 1}
#   create_shared_disk: true
#   shared_disks:
#      - {name: crs, size: 40, count: 1}
#      - {name: data, size: 8, count: 1}
#      - {name: fra, size: 8, count: 1}
#   provisioning: extra-provision/ansible-oracle/vbox-rac-dc2.yml
#   provisioning_env_override: false
